### ISSUE TITLE
Allow user to specify path to file to parse

### ISSUE THREAD

**Issue by dylanhmorris** [APC524/stoched#22]
As far as I can see, the path to the file to parse with the parseFile method is still hard-coded, rather than user-specified at runtime.

**Comment by kevingriffin1** [comment]
I will fix this

**Comment by kevingriffin1** [comment]
Ok it's fixed

**Comment by kevingriffin1** [comment]
I changed it in a hotfix branch and merged it with master. Pull from master to see the change
